/*
 */
package interfaz;

import accesoDatos.EmpleadosDB;
import static interfaz.Dialogs.creaDialogError;
import static interfaz.Dialogs.creaDialogWarning;
import clases.Oficina;
import controlador.Controlador;
import excepciones.CargaDatosException;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import observador.ObservadorEmpleado;
import personas.Empleado;
import personas.TipoEmpleados;

/**
 * @author Escoz
 */
public class VistaPrincipal extends JFrame implements ObservadorEmpleado {
    
    private final Controlador controlador;
    
    private DefaultComboBoxModel<Object> modeloCombo_oficinas;
    private DefaultComboBoxModel<String> modeloCombo_empleados;
    
    private ModeloTablaEmpleadosSueldo modeloTablaEmpleadosSueldo;
    private ModeloTablaEmpleadosSimple modeloTablaEmpleadosSimple;
    private boolean isModeloSueldo;
    
    private final static String SIN_SELECCION = " Sin selección -";

    /**
     * Creates new form VistaPrincipal
     *
     * @param controlador Controlador de la aplicacion
     */
    public VistaPrincipal(Controlador controlador) {
        initComponents();
        
        this.controlador = controlador;
        
        cargaComboEmpelados();
        cargaComboOficinas();
        muestraEmpleadosSinSueldo();
    }

    /**
     * Carga todos los empleados en la tabla principal
     */
    private void muestraEmpleadosSinSueldo() {
        try {
            ArrayList<Empleado> lista_empleados = controlador.leeEmpleados();

            /* Elegimos el modelo simple y añadimos todos los empleados */
            tabla_empleados.setModel(modeloTablaEmpleadosSimple);
            isModeloSueldo = false;
            modeloTablaEmpleadosSimple.addEmpleados(lista_empleados);
            
        } catch (CargaDatosException ex) {
            creaDialogError(this, ex.getMessage(), "Empleados");
        }
    }
    
    private void muestraEmpleadosSueldo(ArrayList<Empleado> lista_empleados, int mes) {
        /* Elegimos el modelo de sueldo y añadimos todos los empleados */
        tabla_empleados.setModel(modeloTablaEmpleadosSueldo);
        isModeloSueldo = true;
        modeloTablaEmpleadosSueldo.addEmpleados(lista_empleados, mes);
    }

    /**
     * Carga los tipos de empleados disponibles en el combo box
     *
     * @param tipos_empleados Lista con los tipos de empleados
     */
    private void cargaComboEmpelados() {
        modeloCombo_empleados.removeAllElements();
        modeloCombo_empleados.addElement(SIN_SELECCION);
        for (TipoEmpleados tipo : TipoEmpleados.values()) {
            modeloCombo_empleados.addElement(tipo.name());
        }
    }

    /**
     * Carga las oficinas de la BBDD, en caso de no poder genera un mensaje de error
     */
    private void cargaComboOficinas() {
        try {
            ArrayList<Oficina> oficinas = controlador.leeOficinas();
            modeloCombo_oficinas.removeAllElements();
            modeloCombo_oficinas.addElement(SIN_SELECCION);
            modeloCombo_oficinas.addElement("Todas");
            modeloCombo_oficinas.addAll(oficinas);
            
        } catch (CargaDatosException ex) {
            creaDialogError(this, ex.getMessage(), "Oficinas");
        }
    }
    
    @Override
    public void cambioEmpleados() {
        if (isModeloSueldo) {
            boton_buscarActionPerformed(null);
        } else {
            muestraEmpleadosSinSueldo();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_empleados = new TablaColores();
        panel_filtros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        modeloCombo_oficinas = new DefaultComboBoxModel<>();
        combo_oficina = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        modeloCombo_empleados = new DefaultComboBoxModel<>();
        combo_empleado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        combo_mes = new javax.swing.JComboBox<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        boton_buscar = new javax.swing.JButton();
        boton_limpiar = new javax.swing.JButton();
        panel_botones = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        boton_imprimir = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        boton_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EmpresaApp");
        setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tabla_empleados.setModel(modeloTablaEmpleadosSueldo = new interfaz.ModeloTablaEmpleadosSueldo());
        tabla_empleados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tabla_empleados.getTableHeader().setReorderingAllowed(false);
        modeloTablaEmpleadosSimple = new ModeloTablaEmpleadosSimple();
        tabla_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_empleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_empleados);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        panel_filtros.setMinimumSize(new java.awt.Dimension(0, 35));
        panel_filtros.setPreferredSize(new java.awt.Dimension(0, 50));
        panel_filtros.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Oficina");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panel_filtros.add(jLabel1, gridBagConstraints);

        combo_oficina.setModel(modeloCombo_oficinas);
        combo_oficina.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panel_filtros.add(combo_oficina, gridBagConstraints);

        jLabel2.setText("Empleado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panel_filtros.add(jLabel2, gridBagConstraints);

        combo_empleado.setModel(modeloCombo_empleados);
        combo_empleado.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panel_filtros.add(combo_empleado, gridBagConstraints);

        jLabel3.setText("Mes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panel_filtros.add(jLabel3, gridBagConstraints);

        combo_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panel_filtros.add(combo_mes, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        panel_filtros.add(filler3, gridBagConstraints);

        boton_buscar.setBackground(new java.awt.Color(51, 153, 255));
        boton_buscar.setForeground(new java.awt.Color(255, 255, 255));
        boton_buscar.setText("Buscar");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panel_filtros.add(boton_buscar, gridBagConstraints);

        boton_limpiar.setText("Limpiar");
        boton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_limpiarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.1;
        panel_filtros.add(boton_limpiar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 5, 10);
        getContentPane().add(panel_filtros, gridBagConstraints);

        panel_botones.setMinimumSize(new java.awt.Dimension(0, 50));
        panel_botones.setPreferredSize(new java.awt.Dimension(0, 50));
        panel_botones.setLayout(new javax.swing.BoxLayout(panel_botones, javax.swing.BoxLayout.LINE_AXIS));
        panel_botones.add(filler1);

        boton_imprimir.setText("Imprimir");
        boton_imprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_imprimir.setPreferredSize(new java.awt.Dimension(80, 23));
        panel_botones.add(boton_imprimir);
        panel_botones.add(filler2);

        boton_salir.setBackground(new java.awt.Color(255, 102, 102));
        boton_salir.setForeground(new java.awt.Color(255, 255, 255));
        boton_salir.setText("Salir");
        boton_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });
        panel_botones.add(boton_salir);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        getContentPane().add(panel_botones, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_boton_salirActionPerformed

    private void boton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_limpiarActionPerformed
        combo_empleado.setSelectedIndex(0);
        combo_oficina.setSelectedIndex(0);
        combo_mes.setSelectedIndex(0);
        muestraEmpleadosSinSueldo();
    }//GEN-LAST:event_boton_limpiarActionPerformed

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed
        String empleado = (String) combo_empleado.getSelectedItem();
        String oficina;

        /* Evitamos busquedas raras */
        if (empleado.equals(SIN_SELECCION) || combo_oficina.getSelectedIndex() == 0) {
            creaDialogWarning(this, "Selecciona un empleado y oficina", "Busqueda");
            return;
        }

        /* Hacemos la seleccion de oficinas */
        if (combo_oficina.getSelectedIndex() == 1) {
            oficina = "Todas";
        } else {
            oficina = ((Oficina) combo_oficina.getSelectedItem()).getCodigo();
        }
        
        try {
            muestraEmpleadosSueldo(controlador.buscaEmpleados(new String[]{oficina, empleado}),
                    combo_mes.getSelectedIndex() + 1);
        } catch (CargaDatosException ex) {
            creaDialogError(this, ex.getMessage(), "Busqueda");
        }
    }//GEN-LAST:event_boton_buscarActionPerformed

    private void tabla_empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_empleadosMouseClicked
        int fila_actual = tabla_empleados.rowAtPoint(evt.getPoint());
        Empleado empleado;
        
        if (isModeloSueldo) {
            empleado = ((ModeloTablaEmpleadosSueldo) tabla_empleados.getModel()).getEmpleado(fila_actual);
        } else {
            empleado = ((ModeloTablaEmpleadosSimple) tabla_empleados.getModel()).getEmpleado(fila_actual);
        }
        
        DialogoEmpleado dialogoEmpleado = new DialogoEmpleado(this, true, empleado);
        dialogoEmpleado.setVisible(true);

        /* Si se desea eliminar este empleado */
        if (dialogoEmpleado.getBorrarEmpleado()) {
            EmpleadosDB.eliminaEmpleado(empleado.getDni());
        }
    }//GEN-LAST:event_tabla_empleadosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_buscar;
    private javax.swing.JButton boton_imprimir;
    private javax.swing.JButton boton_limpiar;
    private javax.swing.JButton boton_salir;
    private javax.swing.JComboBox<String> combo_empleado;
    private javax.swing.JComboBox<String> combo_mes;
    private javax.swing.JComboBox<Object> combo_oficina;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_botones;
    private javax.swing.JPanel panel_filtros;
    private javax.swing.JTable tabla_empleados;
    // End of variables declaration//GEN-END:variables
}
