/*
 */
package interfaz;

import static interfaz.Dialogs.creaDialogError;
import accesoDatos.*;
import clases.Oficina;
import excepciones.CargaDatosException;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import personas.Empleado;

/**
 * @author Escoz
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private DefaultComboBoxModel<Object> modeloCombo_oficinas;
    private DefaultComboBoxModel<String> modeloCombo_empleados;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        abreConexionDB();
        
        initComponents();
        
        cargaComboOficinas();
        cargaEmpleadosTabla();
    }

    /**
     * Abre la conexion con la BBDD, en caso de error muestra un mensaje y para la ejecución.
     */
    private void abreConexionDB() {
        try {
            Conexion.abreConexion();
        } catch (SQLException ex) {
            creaDialogError(this, "No es posible acceder a la BBDD", "Conexión");
            System.exit(1);
        }
    }

    /**
     * Carga todos los empleados en la tabla principal
     */
    private void cargaEmpleadosTabla() {
        try {
            ArrayList<Empleado> lisa_empleados = EmpleadosDB.leeEmpleados();
            ArrayList<String> tipos_empleados = new ArrayList<>();
            
            for (Empleado empleado : lisa_empleados) {
                String tipo = empleado.getClass().getSimpleName();
                
                if (!tipos_empleados.contains(tipo)) {
                    tipos_empleados.add(tipo);
                }
            }
            
            cargaComboEmpelados(tipos_empleados);
            
        } catch (CargaDatosException ex) {
            creaDialogError(this, ex.getMessage(), "Empleados");
        }
    }

    /**
     * Carga los tipos de empleados disponibles en el combo box
     *
     * @param tipos_empleados Lista con los tipos de empleados
     */
    private void cargaComboEmpelados(ArrayList<String> tipos_empleados) {
        modeloCombo_empleados.removeAllElements();
        modeloCombo_empleados.addElement("- Sin selección -");
        for (String tipo_empleado : tipos_empleados) {
            modeloCombo_empleados.addElement(tipo_empleado);
        }
    }

    /**
     * Carga las oficinas de la BBDD, en caso de no poder genera un mensaje de error
     */
    private void cargaComboOficinas() {
        try {
            ArrayList<Oficina> oficinas = OficinasDB.leeOficinas();
            modeloCombo_oficinas.removeAllElements();
            modeloCombo_oficinas.addElement("- Sin selección -");
            modeloCombo_oficinas.addAll(oficinas);
            
        } catch (CargaDatosException ex) {
            creaDialogError(this, ex.getMessage(), "Oficinas");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panel_filtros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        modeloCombo_oficinas = new DefaultComboBoxModel<>();
        combo_oficina = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        modeloCombo_empleados = new DefaultComboBoxModel<>();
        combo_empleado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        boton_buscar = new javax.swing.JButton();
        boton_limpiar = new javax.swing.JButton();
        panel_botones = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        boton_imprimir = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        boton_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EmpresaApp 1.0");
        setPreferredSize(new java.awt.Dimension(900, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        panel_filtros.setMinimumSize(new java.awt.Dimension(0, 35));
        panel_filtros.setPreferredSize(new java.awt.Dimension(0, 50));
        panel_filtros.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Oficina");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panel_filtros.add(jLabel1, gridBagConstraints);

        combo_oficina.setModel(modeloCombo_oficinas);
        combo_oficina.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panel_filtros.add(combo_oficina, gridBagConstraints);

        jLabel2.setText("Empleado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panel_filtros.add(jLabel2, gridBagConstraints);

        combo_empleado.setModel(modeloCombo_empleados);
        combo_empleado.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panel_filtros.add(combo_empleado, gridBagConstraints);

        jLabel3.setText("Mes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panel_filtros.add(jLabel3, gridBagConstraints);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panel_filtros.add(jComboBox3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        panel_filtros.add(filler3, gridBagConstraints);

        boton_buscar.setBackground(new java.awt.Color(51, 153, 255));
        boton_buscar.setForeground(new java.awt.Color(255, 255, 255));
        boton_buscar.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panel_filtros.add(boton_buscar, gridBagConstraints);

        boton_limpiar.setText("Limpiar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.1;
        panel_filtros.add(boton_limpiar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 5, 10);
        getContentPane().add(panel_filtros, gridBagConstraints);

        panel_botones.setMinimumSize(new java.awt.Dimension(0, 50));
        panel_botones.setPreferredSize(new java.awt.Dimension(0, 50));
        panel_botones.setLayout(new javax.swing.BoxLayout(panel_botones, javax.swing.BoxLayout.LINE_AXIS));
        panel_botones.add(filler1);

        boton_imprimir.setText("Imprimir");
        boton_imprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_imprimir.setPreferredSize(new java.awt.Dimension(80, 23));
        panel_botones.add(boton_imprimir);
        panel_botones.add(filler2);

        boton_salir.setBackground(new java.awt.Color(255, 102, 102));
        boton_salir.setForeground(new java.awt.Color(255, 255, 255));
        boton_salir.setText("Salir");
        boton_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });
        panel_botones.add(boton_salir);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        getContentPane().add(panel_botones, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_boton_salirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_buscar;
    private javax.swing.JButton boton_imprimir;
    private javax.swing.JButton boton_limpiar;
    private javax.swing.JButton boton_salir;
    private javax.swing.JComboBox<String> combo_empleado;
    private javax.swing.JComboBox<Object> combo_oficina;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panel_botones;
    private javax.swing.JPanel panel_filtros;
    // End of variables declaration//GEN-END:variables
}
