/*
 */
package vistas;

import controlador.Controlador;

/**
 *
 * @author Escoz
 */
public class DialogoInicial extends javax.swing.JDialog {

    private final Controlador controlador;

    /**
     * Creates new form DialogoInicial
     *
     * @param parent
     * @param modal
     */
    public DialogoInicial(java.awt.Frame parent, boolean modal, Controlador controlador) {
        super(parent, modal);
        initComponents();

        this.controlador = controlador;
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        label_logo = new javax.swing.JLabel();
        panel_botones = new javax.swing.JPanel();
        boton_nominas = new javax.swing.JButton();
        boton_empleados = new javax.swing.JButton();
        boton_oficinas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hyperion App");
        setMaximumSize(new java.awt.Dimension(2147483647, 178));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hyperion_pandora.png"))); // NOI18N
        getContentPane().add(label_logo);

        panel_botones.setMaximumSize(new java.awt.Dimension(32767, 178));
        panel_botones.setPreferredSize(new java.awt.Dimension(300, 178));
        panel_botones.setLayout(new java.awt.GridBagLayout());

        boton_nominas.setBackground(new java.awt.Color(51, 153, 255));
        boton_nominas.setForeground(new java.awt.Color(255, 255, 255));
        boton_nominas.setText("Nominas");
        boton_nominas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_nominasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 10);
        panel_botones.add(boton_nominas, gridBagConstraints);

        boton_empleados.setText("Crear empleado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 10);
        panel_botones.add(boton_empleados, gridBagConstraints);

        boton_oficinas.setText("Crear oficina");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 10);
        panel_botones.add(boton_oficinas, gridBagConstraints);

        getContentPane().add(panel_botones);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void boton_nominasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_nominasActionPerformed
        this.setVisible(false);
        controlador.cambiaVentana(Controlador.VISTA_NOMINAS);
    }//GEN-LAST:event_boton_nominasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_empleados;
    private javax.swing.JButton boton_nominas;
    private javax.swing.JButton boton_oficinas;
    private javax.swing.JLabel label_logo;
    private javax.swing.JPanel panel_botones;
    // End of variables declaration//GEN-END:variables
}
