/*
 */
package vistas;

import javax.swing.DefaultListModel;
import empleados.Administrativo;
import empleados.Analista;
import empleados.Empleado;
import empleados.Programador;
import empleados.Tecnicos;
import empleados.Vendedor;

/**
 *
 * @author Escoz
 */
public class DialogoEmpleado extends javax.swing.JDialog {

    private boolean eliminar_empleado = false;
    private Empleado empleado;

    /**
     * Creates new form DialogoEmpleado
     *
     * @param parent
     * @param modal
     * @param empleado
     */
    public DialogoEmpleado(java.awt.Frame parent, boolean modal, Empleado empleado) {
        super(parent, modal);
        initComponents();
        this.empleado = empleado;

        rellenaDatos();
        setLocationRelativeTo(parent);
    }

    private void rellenaDatos() {

        campo_dni.setText(empleado.getDni());
        campo_nombre.setText(empleado.getNombreCompleto());
        campo_direccion.setText(empleado.getDireccion().toString());
        campo_oficina.setText(empleado.getOficina().toString());
        campo_puesto.setText(empleado.getClass().getSimpleName());

        DefaultListModel<String> modelo_lista = new DefaultListModel<>();
        /* Si es un tecnico rellenamos la lista de tecnologias */
        if (empleado instanceof Tecnicos tecnico) {
            modelo_lista.addAll(tecnico.getTecnologias());
        } else {
            modelo_lista.addElement("- Sin tecnologías -");
        }
        lista_tecnologias.setModel(modelo_lista);

        /* Segun el tipo de empleado rellenamos el ultimo campo */
        if (empleado instanceof Analista analista) {
            label_multiple.setText("Titulación");
            campo_multiple.setText(analista.getTitulacion());
        } else if (empleado instanceof Administrativo administrativo) {
            label_multiple.setText("Ofimatica");
            campo_multiple.setText(administrativo.getNivelOfimatica().name());
        } else if (empleado instanceof Programador programador) {
            label_multiple.setText("Experiencia");
            campo_multiple.setText(programador.getNivel_experiencia().name());
        } else if (empleado instanceof Vendedor vendedor) {
            label_multiple.setText("Zona");
            campo_multiple.setText(String.valueOf(vendedor.getZona()));
        }
    }

    public boolean getBorrarEmpleado() {
        return eliminar_empleado;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_tecnologias = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_tecnologias = new javax.swing.JList<>();
        panel_datos = new javax.swing.JPanel();
        label_dni = new javax.swing.JLabel();
        campo_dni = new javax.swing.JTextField();
        label_nombre = new javax.swing.JLabel();
        campo_nombre = new javax.swing.JTextField();
        label_direccion = new javax.swing.JLabel();
        campo_direccion = new javax.swing.JTextField();
        label_oficina = new javax.swing.JLabel();
        campo_oficina = new javax.swing.JTextField();
        label_puesto = new javax.swing.JLabel();
        campo_puesto = new javax.swing.JTextField();
        boton_eliminar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        label_multiple = new javax.swing.JLabel();
        campo_multiple = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos empleado");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panel_tecnologias.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de tecnologías"));
        panel_tecnologias.setMaximumSize(new java.awt.Dimension(175, 32767));
        panel_tecnologias.setMinimumSize(new java.awt.Dimension(175, 39));
        panel_tecnologias.setPreferredSize(new java.awt.Dimension(175, 4));
        panel_tecnologias.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));

        lista_tecnologias.setForeground(new java.awt.Color(51, 51, 51));
        lista_tecnologias.setFocusable(false);
        jScrollPane1.setViewportView(lista_tecnologias);

        panel_tecnologias.add(jScrollPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        getContentPane().add(panel_tecnologias, gridBagConstraints);

        panel_datos.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panel_datos.setMinimumSize(new java.awt.Dimension(400, 0));
        panel_datos.setPreferredSize(new java.awt.Dimension(400, 300));
        panel_datos.setLayout(new java.awt.GridBagLayout());

        label_dni.setText("DNI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 10);
        panel_datos.add(label_dni, gridBagConstraints);

        campo_dni.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panel_datos.add(campo_dni, gridBagConstraints);

        label_nombre.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 10);
        panel_datos.add(label_nombre, gridBagConstraints);

        campo_nombre.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panel_datos.add(campo_nombre, gridBagConstraints);

        label_direccion.setText("Dirección");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 10);
        panel_datos.add(label_direccion, gridBagConstraints);

        campo_direccion.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panel_datos.add(campo_direccion, gridBagConstraints);

        label_oficina.setText("Oficina");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 10);
        panel_datos.add(label_oficina, gridBagConstraints);

        campo_oficina.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panel_datos.add(campo_oficina, gridBagConstraints);

        label_puesto.setText("Puesto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 10);
        panel_datos.add(label_puesto, gridBagConstraints);

        campo_puesto.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panel_datos.add(campo_puesto, gridBagConstraints);

        boton_eliminar.setBackground(new java.awt.Color(255, 102, 102));
        boton_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        boton_eliminar.setText("Eliminar");
        boton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 5);
        panel_datos.add(boton_eliminar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        panel_datos.add(filler1, gridBagConstraints);

        label_multiple.setText("n/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 10);
        panel_datos.add(label_multiple, gridBagConstraints);

        campo_multiple.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panel_datos.add(campo_multiple, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        getContentPane().add(panel_datos, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eliminarActionPerformed
        eliminar_empleado = true;
        this.setVisible(false);
    }//GEN-LAST:event_boton_eliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_eliminar;
    private javax.swing.JTextField campo_direccion;
    private javax.swing.JTextField campo_dni;
    private javax.swing.JTextField campo_multiple;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JTextField campo_oficina;
    private javax.swing.JTextField campo_puesto;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_direccion;
    private javax.swing.JLabel label_dni;
    private javax.swing.JLabel label_multiple;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_oficina;
    private javax.swing.JLabel label_puesto;
    private javax.swing.JList<String> lista_tecnologias;
    private javax.swing.JPanel panel_datos;
    private javax.swing.JPanel panel_tecnologias;
    // End of variables declaration//GEN-END:variables
}
